# https://eslint.org/docs/rules/
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended' # https://github.com/yannickcr/eslint-plugin-react#configuration
plugins:
  - 'babel'
settings:
  react:
    version: 'detect'
parser: 'babel-eslint'
parserOptions:
  # ecmaVersion: 2018
  # ecmaVersion: 7
  # ecmaVersion: 5
  sourceType: module
  # files:
  #   -
  #     patterns: '**/*.jsx'
rules:
  no-unused-vars:
    - warn
    -
      vars: local
      varsIgnorePattern: ^_
  # indent:
  #   - warn
  #   - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - warn
  #   - single
  semi:
    - error
    - always
# globals:
#   modules: true
#   config: true
